/** Shared demo portfolio jobs and candidates (6 roles × 3 applicants). */

export const DEMO_PORTFOLIO_JOBS = [
  { id: 'JOB-INTERN-001', title: 'Software Engineering Intern', team: 'Engineering', location: 'Austin, TX', stage: 'Open', position_level: 'internship' },
  { id: 'JOB-ASSOC-001', title: 'Associate Product Manager', team: 'Product', location: 'Chicago, IL', stage: 'Screening', position_level: 'entry' },
  { id: 'JOB-MID-001', title: 'Data Analyst II', team: 'Analytics', location: 'Remote (US)', stage: 'Hiring Team Review', position_level: 'mid' },
  { id: 'JOB-SENIOR-001', title: 'Senior Product Manager', team: 'Product', location: 'New York, NY', stage: 'Interviewing', position_level: 'senior' },
  { id: 'JOB-STAFF-001', title: 'Staff Data Engineer', team: 'Data Platform', location: 'Seattle, WA', stage: 'Screening', position_level: 'senior' },
  { id: 'JOB-DIRECTOR-001', title: 'Director, Talent Operations', team: 'People Ops', location: 'San Francisco, CA', stage: 'Draft', position_level: 'senior' },
];

export const DEMO_PORTFOLIO_CANDIDATES = [
  {
    id: 'APP-INT-1001',
    jobId: 'JOB-INTERN-001',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@example.com',
    phone: '512-555-0101',
    source: 'Sample data',
    pipeline: 'shortlisted_interview',
    quality: 'strong',
    authenticity: 96,
    integrity: { focus_loss_count: 0, paste_attempts: 0 },
    resume:
      'Aarav Mehta | B.S. Computer Science (2026), UT Austin. SWE Intern at FinNest (Summer 2025): built React dashboard module, improved API response caching and reduced page latency by 18%. Projects: distributed key-value store in Go, interview scheduler with Node/SQLite. Skills: JavaScript, TypeScript, React, Node.js, Python, SQL, GitHub Actions.',
  },
  {
    id: 'APP-INT-1002',
    jobId: 'JOB-INTERN-001',
    name: 'Nora Fields',
    email: 'nora.fields@example.com',
    phone: '512-555-0102',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'average',
    authenticity: 84,
    integrity: { focus_loss_count: 1, paste_attempts: 0 },
    resume:
      'Nora Fields | B.S. Information Systems (2026), Texas State University. QA + automation intern at retail startup: wrote Cypress smoke tests and bug reports. Coursework in databases, web apps, and systems design. Skills: JavaScript basics, SQL, Postman, Jira, Figma.',
  },
  {
    id: 'APP-INT-1003',
    jobId: 'JOB-INTERN-001',
    name: 'Ethan Cole',
    email: 'ethan.cole@example.com',
    phone: '512-555-0103',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'weak',
    authenticity: 62,
    integrity: { focus_loss_count: 4, paste_attempts: 2 },
    resume:
      'Ethan Cole | Self-taught developer. Built small websites for local clubs and basic todo app in React. Looking for first internship to gain production experience. Skills: HTML/CSS, JavaScript, beginner React.',
  },
  {
    id: 'APP-ASC-2001',
    jobId: 'JOB-ASSOC-001',
    name: 'Elena Vasquez',
    email: 'elena.vasquez@example.com',
    phone: '773-555-0201',
    source: 'Sample data',
    pipeline: 'shortlisted_interview',
    quality: 'strong',
    authenticity: 98,
    integrity: { focus_loss_count: 0, paste_attempts: 0 },
    resume:
      'Elena Vasquez | B.A. Economics, Northwestern (2024). Product Analyst Intern at BeaconHire: owned candidate funnel tracking in Amplitude, coordinated discovery interviews, and helped ship application form improvements that increased completion rate by 14%. Skills: SQL, Figma, Jira, product writing, stakeholder communication.',
  },
  {
    id: 'APP-ASC-2002',
    jobId: 'JOB-ASSOC-001',
    name: 'Jordan Rivera',
    email: 'jordan.rivera@example.com',
    phone: '773-555-0202',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'average',
    authenticity: 89,
    integrity: { focus_loss_count: 1, paste_attempts: 0 },
    resume:
      'Jordan Rivera | B.S. Business Analytics, UIUC (2024). Product internship at PayFlow (10 weeks): user research, sprint support, dashboard updates. Led campus product club and organized two student hackathons.',
  },
  {
    id: 'APP-ASC-2003',
    jobId: 'JOB-ASSOC-001',
    name: 'Mina Patel',
    email: 'mina.patel@example.com',
    phone: '773-555-0203',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'weak',
    authenticity: 58,
    integrity: { focus_loss_count: 6, paste_attempts: 3 },
    resume:
      'Mina Patel | Product coordinator with 1.5 years startup experience supporting backlog and QA tracking. Assisted PMs with release notes and analytics requests. Tools: Jira, Sheets, Trello.',
  },
  {
    id: 'APP-MID-3001',
    jobId: 'JOB-MID-001',
    name: 'Sofia Nguyen',
    email: 'sofia.nguyen@example.com',
    phone: '646-555-0301',
    source: 'Sample data',
    pipeline: 'interview_scheduled',
    quality: 'strong',
    authenticity: 95,
    integrity: { focus_loss_count: 0, paste_attempts: 0 },
    resume:
      'Sofia Nguyen | Data Analyst II with 4 years experience (e-commerce + SaaS). At NorthSquare, redesigned executive KPI model, built dbt marts, and reduced reporting lag from 2 days to 3 hours. SQL and BI specialist with A/B test and funnel analysis ownership.',
  },
  {
    id: 'APP-MID-3002',
    jobId: 'JOB-MID-001',
    name: 'Caleb Morris',
    email: 'caleb.morris@example.com',
    phone: '646-555-0302',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'average',
    authenticity: 86,
    integrity: { focus_loss_count: 1, paste_attempts: 0 },
    resume:
      'Caleb Morris | BI Analyst with 3 years in healthcare operations. Built Tableau dashboards and recurring SQL reports for clinical staffing and patient throughput. Comfortable translating business questions into metrics.',
  },
  {
    id: 'APP-MID-3003',
    jobId: 'JOB-MID-001',
    name: 'Liam Torres',
    email: 'liam.torres@example.com',
    phone: '646-555-0303',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'weak',
    authenticity: 67,
    integrity: { focus_loss_count: 3, paste_attempts: 1 },
    resume:
      'Liam Torres | Reporting analyst at local nonprofit. Maintains monthly spreadsheets and basic dashboards. Limited SQL depth but interested in growing into product analytics.',
  },
  {
    id: 'APP-SNR-4001',
    jobId: 'JOB-SENIOR-001',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    phone: '212-555-0401',
    source: 'Sample data',
    pipeline: 'final_review',
    quality: 'strong',
    authenticity: 91,
    integrity: { focus_loss_count: 0, paste_attempts: 0 },
    resume:
      'Priya Sharma | Product leader with 7 years in B2B SaaS. Senior PM at BloomDesk: launched approvals and analytics modules, grew attached ARR by $4.7M, and improved retention by 9 points. Prior experience in fintech operations and customer discovery. Tools: SQL, Amplitude, Figma, Jira.',
  },
  {
    id: 'APP-SNR-4002',
    jobId: 'JOB-SENIOR-001',
    name: 'Marcus Chen',
    email: 'marcus.chen@example.com',
    phone: '212-555-0402',
    source: 'Sample data',
    pipeline: 'shortlisted_interview',
    quality: 'average',
    authenticity: 74,
    integrity: { focus_loss_count: 4, paste_attempts: 2 },
    resume:
      'Marcus Chen | Senior PM, 9 years SaaS. Led platform analytics rollout and enterprise roadmap planning. Strong technical fluency in data products and API integrations. MBA, Northwestern Kellogg.',
  },
  {
    id: 'APP-SNR-4003',
    jobId: 'JOB-SENIOR-001',
    name: 'Olivia Grant',
    email: 'olivia.grant@example.com',
    phone: '212-555-0403',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'weak',
    authenticity: 52,
    integrity: { focus_loss_count: 8, paste_attempts: 4 },
    resume:
      'Olivia Grant | Product manager with 3 years at two startups. Experience includes feature tickets and stakeholder meetings, but limited ownership of roadmap strategy, experimentation, and commercial outcomes.',
  },
  {
    id: 'APP-STF-5001',
    jobId: 'JOB-STAFF-001',
    name: 'Daniel Okafor',
    email: 'daniel.okafor@example.com',
    phone: '206-555-0501',
    source: 'Sample data',
    pipeline: 'interview_scheduled',
    quality: 'strong',
    authenticity: 94,
    integrity: { focus_loss_count: 0, paste_attempts: 0 },
    resume:
      'Daniel Okafor | Staff Data Engineer, 10 years. Built event-driven data platform on Kafka + Snowflake serving 45 product squads. Reduced pipeline failures by 63% and cut compute cost by 27% with tiered storage strategy. Led architecture guild and mentoring program.',
  },
  {
    id: 'APP-STF-5002',
    jobId: 'JOB-STAFF-001',
    name: 'Grace Kim',
    email: 'grace.kim@example.com',
    phone: '206-555-0502',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'average',
    authenticity: 88,
    integrity: { focus_loss_count: 1, paste_attempts: 0 },
    resume:
      'Grace Kim | Senior Data Engineer with 6 years in ad-tech and fintech. Built Airflow ETL, maintained dbt models, and collaborated with analytics teams on trusted metrics. Strong Python, SQL, and cloud fundamentals.',
  },
  {
    id: 'APP-STF-5003',
    jobId: 'JOB-STAFF-001',
    name: 'Noah Bennett',
    email: 'noah.bennett@example.com',
    phone: '206-555-0503',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'weak',
    authenticity: 61,
    integrity: { focus_loss_count: 5, paste_attempts: 2 },
    resume:
      'Noah Bennett | Data engineer with 2 years ETL maintenance experience. Comfortable with SQL and troubleshooting dashboards; limited architecture ownership at scale.',
  },
  {
    id: 'APP-DIR-6001',
    jobId: 'JOB-DIRECTOR-001',
    name: 'Vanessa Brooks',
    email: 'vanessa.brooks@example.com',
    phone: '415-555-0601',
    source: 'Sample data',
    pipeline: 'interview_completed',
    quality: 'strong',
    authenticity: 93,
    integrity: { focus_loss_count: 0, paste_attempts: 0 },
    resume:
      'Vanessa Brooks | Director of Talent Operations with 12 years experience scaling hiring systems in hypergrowth SaaS. Built structured interviewing program across 1,100 hires/year, reduced time-to-fill by 24%, and led ATS migration with 98% adoption in six months.',
  },
  {
    id: 'APP-DIR-6002',
    jobId: 'JOB-DIRECTOR-001',
    name: 'Henry Walsh',
    email: 'henry.walsh@example.com',
    phone: '415-555-0602',
    source: 'Sample data',
    pipeline: 'final_review',
    quality: 'average',
    authenticity: 85,
    integrity: { focus_loss_count: 1, paste_attempts: 0 },
    resume:
      'Henry Walsh | Senior Recruiting Operations Manager with 8 years leading process redesign, SLA governance, and analytics for distributed recruiting teams. Built dashboarding framework used by TA leadership and finance.',
  },
  {
    id: 'APP-DIR-6003',
    jobId: 'JOB-DIRECTOR-001',
    name: 'Chloe Diaz',
    email: 'chloe.diaz@example.com',
    phone: '415-555-0603',
    source: 'Sample data',
    pipeline: 'application_review',
    quality: 'weak',
    authenticity: 55,
    integrity: { focus_loss_count: 7, paste_attempts: 3 },
    resume:
      'Chloe Diaz | Recruiting coordinator and operations specialist (3 years). Good coordination skills and scheduler administration, but limited enterprise-level process ownership and analytics leadership.',
  },
];

export const DEMO_PORTFOLIO_MARKER = 'demo-portfolio-v1';
